# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20160201_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='ref',
            field=models.CharField(max_length=50, null=True, verbose_name='Ref'),
        ),
    ]
