# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_auto_20160201_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to=b'categories')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.Category')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagen',
            },
        ),
    ]
