# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20160201_1434'),
        ('more', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('features', models.ManyToManyField(to='more.Feature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('order', models.SmallIntegerField(default=10, verbose_name='Order')),
                ('sku', models.CharField(default=b' ', max_length=80, verbose_name=b'Referencia')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            bases=('product.product', models.Model),
        ),
        migrations.CreateModel(
            name='ProductFeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Order')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='more.Feature', verbose_name='Feature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='more.Product')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(through='more.ProductFeatureValue', to='more.Feature'),
        ),
    ]
