# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 00:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20160114_0419'),
        ('more', '0002_auto_20160201_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20, verbose_name=b'nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name=b'apellidos')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            bases=('userprofile.user', models.Model),
        ),
    ]
