# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20160201_1434'),
        ('more', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('discount', models.IntegerField(verbose_name='Descuento')),
                ('discount_unit', models.SmallIntegerField(choices=[(1, 'Valor fijo'), (2, 'Porcentaje')], default=1, verbose_name='Unidad de descuento')),
                ('activated_by_coupon', models.BooleanField(default=False, verbose_name='Activado con cup\xf3n')),
                ('coupon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cupon')),
                ('date_from', models.DateField(verbose_name='Fecha inicio')),
                ('date_to', models.DateField(verbose_name='Fecha fin')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='Prioridad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartDiscountRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('discount', models.IntegerField(verbose_name='Descuento')),
                ('discount_unit', models.SmallIntegerField(choices=[(1, 'Valor fijo'), (2, 'Porcentaje')], default=1, verbose_name='Unidad de descuento')),
                ('activated_by_coupon', models.BooleanField(default=False, verbose_name='Activado con cup\xf3n')),
                ('coupon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cupon')),
                ('date_from', models.DateField(verbose_name='Fecha inicio')),
                ('date_to', models.DateField(verbose_name='Fecha fin')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Descuento de cat\xe1logo',
                'verbose_name_plural': 'Descuentos de cat\xe1logo',
            },
        ),
        migrations.CreateModel(
            name='CatalogDiscountRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.IntegerField(choices=[(1, 'Categoria'), (2, 'Producto')], verbose_name='Tipo')),
                ('use_or', models.BooleanField(default=False, verbose_name='\xd3')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='more.CatalogDiscount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Regla de cat\xe1logo',
                'verbose_name_plural': 'Reglas de cat\xe1logo',
            },
        ),
    ]
